#!/bin/bash
#  Initalize GETH on either the computer or the pi-pucks

# Header
cd $(dirname $0)
source globalconfig

# If data directory is not found
if [ ! -d "$MAIN_DIR" ] 
then
	mkdir $MAIN_DIR
    echo "Created new data directory: $MAIN_DIR"
fi

cd  $MAIN_DIR

# If the GETH process has not been initialized in the data directory
if [ ! -d "$MAIN_DIR/geth" ] 
then
    geth init $GENESIS_FILE \
    --datadir $MAIN_DIR
    echo "Initialized GETH with genesis block: $GENESIS_FILE"
fi

# If is a Pi-Puck
if [ $LOGNAME == "pi" ]
then
	FILE="/boot/pi-puck_id"
	ID=$(cat "$FILE")
else
	ID="100"
fi

geth --datadir ${MAIN_DIR} \
--syncmode "full" \
--port 30311 \
--rpc --rpcaddr "localhost" \
--rpcport 8501 \
--rpcapi "personal,eth,net,web3,txpool,miner" \
--networkid 1515 \
--allow-insecure-unlock \
--lightkdf \
--verbosity 0 \
--nodiscover \
--miner.gasprice "0x1" \
--miner.gastarget "0x1" \
--miner.gaslimit "0x9000000000" \
--nat=extip:"${SUBNET}.${ID}"

echo ${ID}
# --miner.gaslimit "0x9000000000000" \