#!/bin/bash
#  Initalize GETH on either the computer or the pi-pucks

# Header
cd $(dirname $0)
source globalconfig

# # If data directory is not found
# if [ ! -d "$MAIN_DIR" ] 
# then
# 	mkdir $MAIN_DIR
#     echo "Created new data directory: $MAIN_DIR"
# fi

# cd  $MAIN_DIR

# If the GETH process has not been initialized in the blockchain directory
if [ ! -d "$BLOCKCHAINFOLDER/geth" ] 
then
    geth init $GENESIS_FILE \
    --datadir $BLOCKCHAINFOLDER
    echo "Initialized GETH with genesis block: $GENESIS_FILE"
fi

# If is a Pi-Puck
if [ $LOGNAME == "pi" ]
then
	FILE="/boot/pi-puck_id"
	ID=$(cat "$FILE")
else
	ID="100"
fi

geth --datadir ${BLOCKCHAINFOLDER} \
--syncmode "full" \
--port 30311 \
--ws \
--ws.addr "0.0.0.0" \
--ws.port 3335 \
--ws.origins 172.17.0.0 \
--ws.api "personal,eth,net,web3,txpool,miner,admin" \
--networkid 1515 \
--allow-insecure-unlock \
--lightkdf \
--verbosity 5 \
--vmdebug \
--nodiscover \
--miner.gasprice "0x1" \
--miner.gastarget "0x1" \
--miner.gaslimit "0x9000000000" \
--nat=extip:"${SUBNET}.${ID}" 

# Flags to maybe fix the peering delay issue
# --maxpendpeers 5 \
# --config ${MAIN_DIR}/geth/geth-config.toml

echo ${ID}
# --miner.gaslimit "0x9000000000000" \