#!/bin/bash 
# Running this script will disable internet connection

# Disable wpa_supplicant and dhcpcd
systemctl stop wpa_supplicant.service
systemctl stop dhcpcd.service

# Setup Ad-Hoc Network
ip link set wlan0
iw wlan0 set type ibss
ifconfig wlan0 mtu 1499
iwconfig wlan0 channel 3
ip link set wlan0 up
iw wlan0 ibss join AdHocPi 2432

# Configure batman-adv virtual network
modprobe batman-adv
batctl if add wlan0
ip link set up dev wlan0
ip link set up dev bat0

IP =$(cat /boot/pi-puck_id)
ifconfig bat0 172.27.0.${IP}/16