#!/bin/bash  
# Short script to upload the logs folder to the monitoring PC
# Assumptions:
# - Data is containted in logs/ folder and the PC has ID 100

source ../../globalconfig

FILE="/boot/pi-puck_id"
ID=$(cat "$FILE")

touch logs/readme.txt
wait
scp -r logs $MONITOR_NAME@${SUBNET}.${MONITOR_ID}:$MAIN_DIR/results/data/$1/$ID

# mv logs $ID
# wait
# scp -r $ID eksander@${SUBNET}.100:$MAIN_DIR/results/$1/$ID