#!/bin/bash  
# Short script to ping the complete list of Pi-Pucks
# Returns a text file pi-pucks.txt containing the responding Pi-Puck IDs
source ../../globalconfig
> pi-pucks.txt

if [ "$SUBNET" == "172.27.1" ]; then 
	echo "Scanning Ad-Hoc Network..."
	PIPUCK1_ALL=(101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120)
	PIPUCK2_ALL=(201 202 203 204 206 207 208 209 210 211 212 213 214 215 216)
else
	echo "Scanning Router Network..."
	PIPUCK1_ALL=($(nmap -sn $SUBNET.* -oG - | grep '()' | cut -b 17-19))
fi

touch temp.txt

# If user requests slow pinging
if [[ "$1" == "--slow" ]]; then 
	for ID in "${PIPUCK1_ALL[@]}" "${PIPUCK2_ALL[@]}"; do
		( ping -n -c 1 -w 5 $SUBNET.$ID 1>/dev/null 2>&1 && echo $ID  >> temp.txt && printf "%-12s %s\n" $SUBNET.$ID responded) 
	sleep 0.03
	done 
else

	for ID in "${PIPUCK1_ALL[@]}" "${PIPUCK2_ALL[@]}"; do
		( ping -n -c 1 -w 1 $SUBNET.$ID 1>/dev/null 2>&1 && echo $ID  >> temp.txt && printf "%-12s %s\n" $SUBNET.$ID responded) &
		sleep 0.03
	done 
fi

wait
wc -l temp.txt | awk '{ print "Robot Count: " $1 }'
sort -n temp.txt >> pi-pucks.txt
rm temp.txt


# If user requests signal
if [ "$1" == "--signal" ]; then 
	./ssh-all "cd $MAIN_DIR_ROBOTS/control/robots; python3 rgbleds.py"
fi


