#!/bin/bash  
# Short script to ping the complete list of Pi-Pucks
# Returns a text file pi-pucks.txt containing the responding Pi-Puck IDs
# Assumptions:
# - All known Pi-puck IDs are listed in ~/geth-pi-pucks/swarm-control/pi-pucks-all.txt
source globalconfig

IDS_FILE="pi-pucks-all.txt"
SUBNET="172.27.1"

> pi-pucks.txt

touch temp.txt
for ID in $(cat "$IDS_FILE"); do
	( ping -n -c 1 -w 1 $SUBNET.$ID 1>/dev/null 2>&1 && echo $ID  >> temp.txt && printf "%-12s %s\n" $SUBNET.$ID responded) &  
done 
wait

wait
wc -l temp.txt | awk '{ print "Robot Count: " $1 }'
sort -n temp.txt >> pi-pucks.txt
rm temp.txt
cp pi-pucks.txt $WORKING_DIR/control/experiment/