#!/bin/bash  
# Short script to generate and upload a new genesis block
# Assumptions:
# - The Pi-puck IDs (initial sealers) are listed in pi-pucks.txt
# - puppeth is installed

source ../../globalconfig

IDS_FILE="pi-pucks.txt"
NUM_NODES=$(cat "$IDS_FILE" | grep -v ^$ | wc -l)
# NUM_NODES=5

> genesis.conf 

########## Genesis Configurations ############

echo "2" >> genesis.conf  # Manage existing genesis
echo "3" >> genesis.conf  # Remove existing genesis
echo "2" >> genesis.conf  # Configure new genesis
echo "1" >> genesis.conf  # Create new genesis from scratch
echo "2" >> genesis.conf  # Clique - proof-of-authority
echo "15" >> genesis.conf # 15 seconds block time

# List of sealers
for INDEX in $(seq 0 $NUM_NODES);
do
	KEY_FILE=$"key-$INDEX"
    KEY=$(cat "keystore-all/$KEY_FILE")
    echo ${KEY:12:40} >> genesis.conf 
done
echo "" >> genesis.conf 

# Pre-fund all accounts
for INDEX in $(seq 0 $NUM_NODES);
do
    KEY_FILE=$"key-$INDEX"
    KEY=$(cat "keystore-all/$KEY_FILE")
    echo ${KEY:12:40} >> genesis.conf 
done

# Pre-fund the contract address
echo $CONTRACT_ADDRESS >> genesis.conf 
echo "" >> genesis.conf 


echo "yes" >> genesis.conf  # Pre-compile addresses
echo "1515" >> genesis.conf # Netid
echo "2" >> genesis.conf    # Manage existing genesis 
echo "2" >> genesis.conf    # Export genesis configurations

 # Export Path
echo "$MAIN_DIR/genesis" >> genesis.conf 

########## Generate Genesis Block ############
echo "Generating Genesis Block..."
cat "genesis.conf" | nohup puppeth --network=pipucks >/dev/null 2>&1
rm $MAIN_DIR/genesis/pipucks-harmony.json
# rm genesis.conf

########## Compile and Deploy Smart Contract ############
echo "Compiling the Smart Contract..."
solc --overwrite --abi --bin --bin-runtime -o  "$MAIN_DIR/control/robots/scs/build" "$CONTRACT_FILE"
# BINDATA=`cat $MAIN_DIR/control/robots/scs/build/Estimation.bin-runtime`

# echo "Contract address:" `cat $MAIN_DIR/control/robots/scs/contractAddress.txt ` 

# echo "Deploying the Smart Contract..."
# sed -i "s|123\": {|123\": {\n\"code\": \"0xBINDATA\",|g" ${GENESIS_FILE}
# sed -i "s|BINDATA|$BINDATA|g" ${GENESIS_FILE}

# # Change the gas limit
# sed -i "s|0x47b760|0x9000000000000|g" ${GENESIS_FILE}

# # Change the value of the pre-funded accounts
# sed -i "s|\"0x200000000000000000000000000000000000000000000000000000000000000\"|\"0x1236efcbcbb340000\"|g" ${GENESIS_FILE}
# # 0x1236efcbcbb340000 = 21 ether
# # 0xde0b6b3a7640000 = 1 ether

# # Undo for the contract account (first match)
# sed -i "0,/\"0x1236efcbcbb340000\"/s//\"0x200000000000000000000000000000000000000000000000000000000000000\"/" ${GENESIS_FILE}


# # Update the contract ABI to make it compatible with the geth console 
# # (latest solc and latest geth console are incompatibe)
# cp $CONTRACT_ABI ./OLDABI.abi
# sed -e "s|\"stateMutability\":\"payable\"|\"stateMutability\":\"payable\",\"payable\":\"true\"|g" ./OLDABI.abi > $CONTRACT_ABI
# rm ./OLDABI.abi

########## Upload Genesis File ############
echo "Uploading Genesis Block..."
./scp-all $GENESIS_FILE $BASE_FOLDER/genesis
wait