#!/bin/bash  
# Short script to reset the geth data directory and stop running processes

source ../../globalconfig

# Stop GETH Processes 
echo "Stopping GETH"
killall geth
./ssh-all "killall geth"
wait

# Reset GETH folders
echo "Reseting Pi-Puck Chaindata..."
rm -r "$MAIN_DIR" /geth
./ssh-all "rm -r $MAIN_DIR_ROBOTS /geth"
wait

