#!/bin/bash  
# Short script to distribute pre-generated cryptographic keys to Pi-Pucks
# Assumptions:
# - The Pi-puck IDs (initial sealers) are listed in pi-pucks.txt
# - The key files titled "key-i", i = {1, 2 ... n} are in folder keystore-all/
source ../../globalconfig

# Delete file that stores key map
> key-mapping.txt 

# Remove Previous Key Files
./ssh-all "rm -rf $MAIN_DIR_ROBOTS/keystore/*"

wait
# Distribute new key files
INDEX=1
for ID in $(cat "$IDS_FILE"); do
	wait
	KEY_FILE=$"key-$INDEX"
	IP="${PREFIX}${ID}"
	
	scp keystore-all/"$KEY_FILE" "$IP":$MAIN_DIR_ROBOTS/keystore/

	# Return key to Pi-puck ID mapping
	KEY=$(cat "keystore-all/$KEY_FILE")
	echo "$ID $KEY_FILE 0x${KEY:12:40}" >> key-mapping.txt &
	let "INDEX+=1" 
done
