#!/bin/bash  
# Short script to reset blockchain to a clean start with the number of nodes

# Update Responding Pi-Pucks
./ping-all
wait
echo "----//----"

# Reset GETH 
echo "Reseting Geth..."
./reset-geth
wait
echo "----//----"

# Reset the Genesis File
echo "Reseting Genesis Block..."
./reset-genesis
wait
echo "----//----"

# Distribute Keys
echo "Reseting Pi-Puck Keys..."
./reset-keys
wait
echo "----//----"

# # Restart GETH processes
# echo "Rebooting GETH"
# ./ssh-all "sudo systemctl enable geth.service"
# ./ssh-all "sudo systemctl start geth.service"
# wait


