#!/bin/bash  
# Short script to send a file/folder to all robots
# Assumptions:
# - The Pi-puck IDs are listed in pi-pucks.txt
# - Arg1 is the file to send; Arg2 is the folder in /home/pi/
source ../../globalconfig

if [ $# -eq 2 ]; then 
	for ID in $(cat "$IDS_FILE"); do
	IP="${PREFIX}${ID}"
	scp -r "$1" "$IP:/home/pi/$2"  &
	done
	wait
fi

# Customizable list of often uploaded folders/files
if [ $1 == "scs" ]; then 
	solc -o $MAIN_DIR/control/robots/scs/build/ --bin-runtime --abi --overwrite $CONTRACT_FILE
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/control/robots/scs "$IP:$MAIN_DIR_ROBOTS/control/robots/"  &
	done
	wait
fi

if [ $1 == "mainloop" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/control/robots/mainloop.py "$IP:$MAIN_DIR_ROBOTS/control/robots/"  &
	done
	wait
fi

if [ $1 == "control" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/control/robots "$IP:$MAIN_DIR_ROBOTS/control/"  &
	done
	wait
fi

if [ $1 == "all" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/control "$IP:$MAIN_DIR_ROBOTS/"  &
		scp -r $MAIN_DIR/setup-adhoc "$IP:$MAIN_DIR_ROBOTS/"  &
		scp -r $MAIN_DIR/setup-geth "$IP:$MAIN_DIR_ROBOTS/"  &
		scp -r $MAIN_DIR/globalconfig "$IP:$MAIN_DIR_ROBOTS/"  &
		scp -r $MAIN_DIR/README.md "$IP:$MAIN_DIR_ROBOTS/"  &
	done
	wait
fi