#!/bin/bash
# Short script to command all robots via Cluster SSH
# Assumptions:
# - CSSH is installed 
# - The Pi-puck IDs are listed in pi-pucks.txt

source ../../globalconfig

IDS_FILE="pi-pucks.txt"
PREFIX="pi@${SUBNET}."

# Send individual command to each robot
if [ "$#" -eq 1 ]; then
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		ssh "$IP" "$1" &
	done
fi

# Open CSSH console for each robot
if [ "$#" -eq 0 ]; then
ALL_IPS=""
for ID in $(cat "$IDS_FILE"); do
	ALL_IPS="$ALL_IPS ${PREFIX}${ID}"
done
cssh $ALL_IPS 
fi

wait