#!/bin/bash
# Short script to check if the i2c devices are availiable on all robots
# Assumptions:
# - The Pi-puck IDs are listed in pi-pucks.txt
source ../globalconfig

MIN_DEVICES=3
MIN_BATTERY=80

i2cdetect_ALL() {
	local ID=$1
	IP="${PREFIX}${ID}"
	I2CCOUNT=$(ssh "$IP" "sudo i2cdetect -y 4 | grep -E -o ' 1f | 60 | 20 ' | wc -l")
	
	if (($I2CCOUNT < $MIN_DEVICES)); then
		echo "$SUBNET.$ID I2C failed (${I2CCOUNT} devices)"
	else
		echo "$SUBNET.$ID I2C OK (${I2CCOUNT} devices)"    
	fi

}

battery_check_ALL() {
	local ID=$1
	IP="${PREFIX}${ID}"
	BATTERY=$(ssh "$IP" "python ${MAIN_DIR_ROBOTS}/robots/controllers/pi-puck-battery.py"| awk '{print $3}' | grep -Eo '[0-9]+\.[0-9]+') 

	if (( $(echo "$BATTERY < $MIN_BATTERY" | bc -l) )); then
		echo "$SUBNET.$ID Battery failed ($BATTERY%)"
	else
		echo "$SUBNET.$ID Battery OK ($BATTERY%)"
	fi
}

# Check I2C on each robot
for ID in $(cat "$IDS_FILE"); do
	i2cdetect_ALL "$ID" 
done

# Check Battery on each robot
for ID in $(cat "$IDS_FILE"); do
	battery_check_ALL "$ID" 
done
