#!/bin/bash
# Short script to check the battery and i2c status of the robots

source ../globalconfig

MIN_DEVICES=3
MIN_BATTERY=80

i2c_check() {
	local ID=$1

	I2CCOUNT=$(ssh "${PREFIX}${ID}" "sudo i2cdetect -y 4 | grep -E -o ' 1f | 60 | 20 ' | wc -l")
	
	if (($I2CCOUNT < $MIN_DEVICES)); then
		echo "$SUBNET.$ID I2C failed (${I2CCOUNT} devices)"
	else
		echo "$SUBNET.$ID I2C OK (${I2CCOUNT} devices)"    
	fi

}

battery_check() {
	local ID=$1

	BATTERY=$(ssh "${PREFIX}${ID}" "python ${MAIN_DIR_ROBOTS}/robots/controllers/battery.py"| awk '{print $3}' | grep -Eo '[0-9]+\.[0-9]+') 

	if (( $(echo "$BATTERY < $MIN_BATTERY" | bc -l) )); then
		echo "$SUBNET.$ID Battery failed ($BATTERY %)"
	else
		echo "$SUBNET.$ID Battery OK ($BATTERY %)"
	fi
}

# Check I2C on each robot
for ID in $(cat "$IDS_FILE"); do
	i2c_check "$ID" 
done

# Check Battery on each robot
for ID in $(cat "$IDS_FILE"); do
	battery_check "$ID" 
done
