#!/bin/bash  
# Short script to extract log files from all robots listed
# Assumptions:
# - The Pi-puck IDs are listed in pi-pucks.txt
source ../globalconfig

if [ "$#" -eq 1 ]; then
	if [ -d "$MAIN_DIR/results/data/$1" ]; then
	# Take action if $DIR exists. #
	echo "Rewrite folder $MAIN_DIR/results/data/$1? [Y/N]"
	read CONF
	if [ $CONF = "Y" -o $CONF = "y" ]; then
		rm -rfv $MAIN_DIR/results/data/$1
	else
		exit 1
	fi

	fi
	
	mkdir -p $MAIN_DIR/results/data/$1

	# for ID in $(cat "$IDS_FILE"); do
	# 	IP="${PREFIX}${ID}"
	# 	ssh "$IP" "tar -czvf ${MAIN_DIR_ROBOTS}/$ID-geth.tar.gz -C ${MAIN_DIR_ROBOTS}/geth ." &
	# done
	wait
	for ID in $(cat "$IDS_FILE"); do
		scp -r pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/control/robots/logs $MAIN_DIR/results/data/$1/$ID
		# scp -r pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/$ID-geth.tar.gz $MAIN_DIR/results/data/$1/$ID/
		# scp -rf pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/$ID-geth.tar.gz $MAIN_DIR/results/data/$1/$ID

	done
else
	echo "Input record foldername"
fi





# backup
# if [ "$#" -eq 1 ]; then
# 	rm -rfv $MAIN_DIR/results/data/$1 && mkdir -p $MAIN_DIR/results/data/$1
# 	for ID in $(cat "$IDS_FILE"); do
# 		scp -r pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/control/robots/logs $MAIN_DIR/results/data/$1/$ID
# 	done
# else
# 	echo "Input record foldername"
# fi