#!/bin/bash  
# Short script to extract log files from each robot
# robots/logs folder to /results/data/experiment/config/rep

# Arguments: (string) experiment/config

source ../globalconfig

LOGSFOLDER="$MAIN_DIR_ROBOTS/$EXPERIMENT_FOLDER/logs"
DATAFOLDER="$MAIN_DIR/results/data/$1"
PLOTFOLDER="$MAIN_DIR/results/plots/$1"

# Create the experiment directory
mkdir -p $DATAFOLDER $PLOTFOLDER

# Find the latest repetition in that folder
last_rep=$(ls $DATAFOLDER -v | tail -1 | sed 's/^0*//')
new_rep=$(printf "%03d\n" $(($last_rep+1)))

mkdir -p $DATAFOLDER/$new_rep

# # Collect experiment configuration into /logs/
# python3 << END
# import sys, os

# sys.path += [os.environ['EXPERIMENTFOLDER']+'/controllers', \
#              os.environ['EXPERIMENTFOLDER']+'/loop_functions', \
#              os.environ['EXPERIMENTFOLDER']]

# import loop_params as lp
# import control_params as cp

# # Collect the loop parameters
# dict_list = [(param, value) for param, value in lp.params.items() if isinstance(value, dict)]

# # Collect the control parameters
# dict_list.extend([('control', cp.params)])

# # Collect the experiment configuration
# f = open('experimentconfig.sh', 'r')
# experimentconfig = f.read()
# experimentparams = {param:value for param,value in os.environ.items() if param in experimentconfig}
# dict_list.extend([('experiment',experimentparams)])

# savefile = open(os.environ['EXPERIMENTFOLDER'] + '/logs/config.py', 'w+')
# for name, param_dict in dict_list:
#   savefile.write('%s = %s \n' % (name, repr(param_dict)))
# END

cp ../globalconfig $DATAFOLDER
# cp $EXPERIMENTFOLDER/loop_functions/loop_params.py $LOGSFOLDER
# cp $EXPERIMENTFOLDER/controllers/control_params.py $LOGSFOLDER

# Collect geth related logs from docker folder into /logs/
for ID in $(cat "$IDS_FILE"); do
  scp -r $ROBOTS_NAME@$SUBNET.$ID:$LOGSFOLDER $DATAFOLDER/$new_rep/$ID
done

echo "Stored data to: /results/data/$1/$new_rep"

