#!/bin/bash  
# Short script to generate and upload a new genesis block
# Assumptions:
# - puppeth is in PATH

source ../globalconfig

NUM_NODES=$(cat "$IDS_FILE" | grep -v ^$ | wc -l)

> genesis.conf 

########## Genesis Configurations ############

echo "2" >> genesis.conf  # Manage existing genesis
echo "3" >> genesis.conf  # Remove existing genesis
echo "2" >> genesis.conf  # Configure new genesis
echo "1" >> genesis.conf  # Create new genesis from scratch
echo "2" >> genesis.conf  # Clique - proof-of-authority
echo "8" >> genesis.conf # 15 seconds block time

# List of sealers
for ID in $(cat "$IDS_FILE");
do
    KEY=$(cat "$MAIN_DIR/$BLOCKCHAIN_FOLDER/keystores/$ID/$ID")
    echo ${KEY:12:40} >> genesis.conf 
done
echo "" >> genesis.conf 

# Pre-fund all accounts
for ID in $(cat "$IDS_FILE");
do
    KEY=$(cat "$MAIN_DIR/$BLOCKCHAIN_FOLDER/keystores/$ID/$ID")
    echo ${KEY:12:40} >> genesis.conf 
done

# Pre-fund the contract address
CONTRACT_ADDRESS=`cat $MAIN_DIR/blockchain/scs/contractAddress.txt`
echo $CONTRACT_ADDRESS >> genesis.conf 
echo "" >> genesis.conf 

echo "yes" >> genesis.conf  # Pre-compile addresses
echo "1515" >> genesis.conf # Netid
echo "2" >> genesis.conf    # Manage existing genesis 
echo "2" >> genesis.conf    # Export genesis configurations

 # Export Path
echo "$MAIN_DIR/$BLOCKCHAIN_FOLDER/genesis" >> genesis.conf 

########## Generate Genesis Block ############
echo "Generating Genesis Block..."
cat "genesis.conf" | "$MAIN_DIR/monitor/puppeth" --network=pipucks >/dev/null 2>&1
rm $MAIN_DIR/$BLOCKCHAIN_FOLDER/genesis/pipucks-harmony.json
rm genesis.conf

########## Compile and Deploy Smart Contract ############
echo "Compiling the Smart Contract..."

envsubst < $CONTRACT_TEMP > $CONTRACT_FILE
find "$MAIN_DIR/blockchain/scs/build" -mindepth 1 -delete

solc --evm-version berlin --overwrite --abi --bin --bin-runtime -o  "$MAIN_DIR/blockchain/scs/build" "$CONTRACT_FILE"

echo "Deploying the Smart Contract @ 0x$CONTRACT_ADDRESS"

BINDATA=`cat $MAIN_DIR/blockchain/scs/build/$CONTRACT_NAME.bin-runtime`

sed -i "s|123\": {|123\": {\n\"code\": \"0xBINDATA\",|g" ${GENESIS_FILE}
sed -i "s|BINDATA|$BINDATA|g" ${GENESIS_FILE}

# Change the gas limit
sed -i "s|0x47b760|0x9000000000|g" ${GENESIS_FILE}

# Change the value of the pre-funded accounts
sed -i "s|\"0x200000000000000000000000000000000000000000000000000000000000000\"|\"0x1236efcbcbb340000\"|g" ${GENESIS_FILE}
# 0x1236efcbcbb3400000 = 336 ether // 0x1236efcbcbb340000 = 21 ether // 0xde0b6b3a7640000 = 1 ether

# Undo for the contract account (first match)
sed -i "0,/\"0xde0b6b3a7640000\"/s//\"0x200000000000000000000000000000000000000000000000000000000000000\"/" ${GENESIS_FILE}

########## Upload Genesis File and Contract ABI############
echo "Uploading Genesis and ABI to the robots..."
./scp-all genesis
./scp-all abi
wait