#!/bin/bash  
# Short script to reset the geth data directory and stop running processes

source ../globalconfig

# Stop GETH Processes 
echo "Stopping all GETH processes..."
./ssh-all "killall geth 2>/dev/null" &
wait

# Reset GETH folders
echo "Removing Pi-Puck chaindata..."
./ssh-all "rm -r $MAIN_DIR_ROBOTS/$BLOCKCHAIN_FOLDER/geth > /dev/null 2>&1" &
wait

