#!/bin/bash  
# Short script to distribute pre-generated cryptographic keys to Pi-Pucks
# Assumptions:
# - The Pi-puck IDs (initial sealers) are listed in pi-pucks.txt
# - The key files titled "key-i", i = {1, 2 ... n} are in folder keystore-all/
source ../globalconfig

# Delete file that stores key map
> key-mapping.txt 

# Remove Previous Key Files
./ssh-all "rm -rf $MAIN_DIR_ROBOTS/$BLOCKCHAIN_FOLDER/keystore; mkdir $MAIN_DIR_ROBOTS/$BLOCKCHAIN_FOLDER/keystore"

wait

# Distribute new key files
INDEX=1
for ID in $(cat "$IDS_FILE"); do
	KEY_FILE=$MAIN_DIR/$BLOCKCHAIN_FOLDER/keystore-all/$INDEX
	KEY=$(cat "$KEY_FILE")
	IP="${PREFIX}${ID}"

	scp $KEY_FILE $IP:$MAIN_DIR_ROBOTS/$BLOCKCHAIN_FOLDER/keystore/

	# Return key to Pi-puck ID mapping
	echo "$ID 0x${KEY:12:40}" >> key-mapping.txt
	let "INDEX+=1" 
	sleep 0.01
done