#!/bin/bash  
# Short script to send a file/folder to all robots
# Arguments:
# - Arg1 is the file to send in $MAIN_DIR
# - Arg2 is the destination in $MAIN_DIR_ROBOTS
# Alternatively:
# - Arg1 is one pre-set quick option
# Examples:
# 'scp-all scs'      (uploads smart contract build folder)
# 'scp-all mainloop' (uploads the mainloop)
# 'scp-all control'  (uploads the full robot control folder)
# 'scp-all all'      (deletes and restores the main directory)

source ../globalconfig

# Send files to every IP
scp_ALL() {
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/$1 "$IP:$MAIN_DIR_ROBOTS/$2" &
	done
	wait
}

if [ $# -eq 2 ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r "$1" "$IP:$MAIN_DIR_ROBOTS/$2"  &
	done
	wait
fi

# Customizable list of often uploaded folders/files
if [ $1 == "scs" ]; then
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/robots/scs/build "$IP:$MAIN_DIR_ROBOTS/robots/scs" &
	done
	wait
fi

if [ $1 == "globalconfig" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		rsync $MAIN_DIR/globalconfig "$PREFIX$ID:$MAIN_DIR_ROBOTS"
	done
fi

if [ $1 == "genesis" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $GENESIS_FILE "$IP:$MAIN_DIR_ROBOTS/$BLOCKCHAIN_FOLDER/genesis" 
	done
fi

if [ $1 == "custom" ]; then 
		scp_ALL psutil-5.9.5.tar.gz " "
fi

if [ $1 == "scbuild" ]; then 
		scp_ALL blockchain/scs/build blockchain/scs/build
fi

if [ $1 == "abi" ]; then 
		scp_ALL blockchain/scs/build/$CONTRACT_NAME.abi blockchain/scs/build/$CONTRACT_NAME.abi
fi

if [ $1 == "contractaddr" ]; then
	scp_ALL blockchain/scs/contractAddress.txt blockchain/scs/contractAddress.txt
fi

if [ $1 == "setup-geth" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/setup-geth "$IP:$MAIN_DIR_ROBOTS" &
	done
	wait
fi

if [ $1 == "setup-router" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/setup-router "$IP:$MAIN_DIR_ROBOTS" &
	done
	wait
fi


if [ $1 == "setup-adhoc" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		cat /home/eksander/geth-pi-pucks/setup-adhoc | ssh $IP "sudo tee /usr/local/bin/setup-adhoc"
	done
	wait
fi

if [ $1 == "calibration" ]; then
 	scp_ALL robots/calibration/ robots/
fi

if [ $1 == "calibrate-cam" ]; then
 	scp_ALL robots/calibration/calibrate-cam.py robots/calibration/calibrate-cam.py
fi

if [ $1 == "calibrate-gs" ]; then
 	scp_ALL robots/calibration/calibrate-gs.py robots/calibration/calibrate-gs.py
fi

if [ $1 == "sshkeys" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		ssh-copy-id -i ~/.ssh/pi-pucks.pub $IP
	done
	wait
fi

if [ $1 == "calib" ]; then 
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r "$IP:$MAIN_DIR_ROBOTS/robots/calibration/cam/" $MAIN_DIR/robots/calibration/cam/
#		rsync -avz "$IP:$MAIN_DIR_ROBOTS/robots/calibration/gs/" $MAIN_DIR/robots/calibration/gs/
	done
	wait
fi

if [ $1 == "arducam" ]; then
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		scp -r $MAIN_DIR/robots/arducam/ "$IP:$MAIN_DIR_ROBOTS/robots/"  &
	done
	wait
fi

if [ $1 == "blockchain" ]; then
	scp_ALL blockchain/ ""
fi


if [ $1 == "control" ]; then
	scp_ALL robots/controllers/ robots/
fi

if [ $1 == "mainloop" ]; then
	scp_ALL robots/controllers/mainloop.py robots/controllers/mainloop.py
fi

if [ $1 == "colorguidedwalk" ]; then
	scp_ALL robots/controllers/colorguidedwalk.py robots/controllers/colorguidedwalk.py
fi

if [ $1 == "console" ]; then 
	scp_ALL robots/controllers/console.py robots/controllers/console.py
fi

if [ $1 == "aux" ]; then 
	scp_ALL robots/controllers/aux.py robots/controllers/aux.py
fi

if [ $1 == "upcamera" ]; then 
	scp_ALL robots/controllers/upcamera.py robots/controllers/upcamera.py 
fi

# if [ $1 == "all" ]; then 
# 	./ssh-all "rm -r $MAIN_DIR_ROBOTS > /dev/null 2>&1" &
# 	wait
# 	./ssh-all "mkdir $MAIN_DIR_ROBOTS; mkdir $MAIN_DIR_ROBOTS/control; mkdir $MAIN_DIR_ROBOTS/keystore; mkdir $MAIN_DIR_ROBOTS/genesis" &
# 	wait
# 	for ID in $(cat "$IDS_FILE"); do
# 		IP="${PREFIX}${ID}"
# 		scp -r $MAIN_DIR/control/robots "$IP:$MAIN_DIR_ROBOTS/control" &
# 		scp -r $MAIN_DIR/setup-adhoc "$IP:$MAIN_DIR_ROBOTS" &
# 		scp -r $MAIN_DIR/setup-geth "$IP:$MAIN_DIR_ROBOTS" &
# 		scp -r $MAIN_DIR/setup-router "$IP:$MAIN_DIR_ROBOTS" &
# 		scp -r $MAIN_DIR/globalconfig "$IP:$MAIN_DIR_ROBOTS" &
# 		scp -r $MAIN_DIR/README.md "$IP:$MAIN_DIR_ROBOTS" &
# 	done
# 	wait
# fi

# if [ $1 == "testwhite" ]; then 
# 	for ID in $(cat "$IDS_FILE"); do
# 		IP="${PREFIX}${ID}"
# 		scp -r $MAIN_DIR/control/robots/testWhite.py "$IP:$MAIN_DIR_ROBOTS/control/robots/"  &
# 	done
# 	wait
# fi

# if [ $1 == "battery" ]; then 
# 	for ID in $(cat "$IDS_FILE"); do
# 		IP="${PREFIX}${ID}"
# 		scp -r $MAIN_DIR/control/robots/battery.py "$IP:$MAIN_DIR_ROBOTS/control/robots/"  &
# 	done
# 	wait
# fi

# if [ $1 == "pb" ]; then 
# 	for ID in $(cat "$IDS_FILE"); do
# 		IP="${PREFIX}${ID}"
# 		scp -r /home/eksander/geth-pi-pucks/powerbutton.py "$IP:/home/pi/geth-pi-pucks"  &
# 		scp -r /home/eksander/geth-pi-pucks/setup-router "$IP:/home/pi/geth-pi-pucks"  &
# 		scp -r /home/eksander/geth-pi-pucks/powerbutton.service "$IP:/home/pi/geth-pi-pucks"  &
# 	done
# 	wait
# fi


# if [ $1 == "custom1" ]; then 
# 	for ID in $(cat "$IDS_FILE"); do
# 		IP="${PREFIX}${ID}"
# 		scp -r /home/eksander/Pi-pucks/pi-puck/utilities "$IP:$MAIN_DIR_ROBOTS/control/"  &
# 		scp -r /home/eksander/Pi-pucks/RPi.GPIO-0.7.0.tar.gz "$IP:$MAIN_DIR_ROBOTS/control/"  &
# 	done
# 	wait
# fi

# if [ $1 == "custom" ]; then 
# 	for ID in $(cat "$IDS_FILE"); do
# 		IP="${PREFIX}${ID}"
# 		scp -r $MAIN_DIR/control/robots/scikit-image-0.18.2.tar.gz "$IP:$MAIN_DIR_ROBOTS/control/robots/"  &
# 	done
# 	wait
# fi