#!/bin/bash
# Short script to command all robots via Cluster SSH
# Assumptions:
# - The Pi-puck IDs are listed in pi-pucks.txt

source ../globalconfig

# Send individual command to each robot
if [ "$#" -eq 1 ]; then
	for ID in $(cat "$IDS_FILE"); do
		IP="${PREFIX}${ID}"
		ssh "$IP" "$1" &
		sleep 0.02
	done
fi

wait