#!/bin/bash
# Short script to control all robots via SSH
# Arguments:
# - Arg1 is the command to execute in all robots

source ../globalconfig

# Send individual command to each robot
if [ "$#" -eq 1 ]; then
	for ID in $(cat "$IDS_FILE"); do
		ssh "${PREFIX}${ID}" "$1" &
		sleep 0.02
	done
fi

wait