#!/bin/bash  
# Starts an experiment
#
# Options:
# --reset    or -r  : will reset everything blockchain related
# --start    or -s  : will start the experiment
# --startz   or -sz : will start with no visualization
# --logs     or -l  : will display monitor.log for all robots
# --python   or -p  : will display python console for all robots
# Example: 
# . starter -r -s -l -p

source ../globalconfig

echo "+-----------------------------------------------------------+"
echo "MAINFOLDER IS $MAIN_DIR"


for opt in "$@"
do
if [[ $opt == "--ping" || $opt == "-p" ]]; then

echo "+-----------------------------------------------------------+"
echo "Pinging robots..."
./ping-all
wait

## Check responding robot count
#NUM_RESP=$(wc -l < pi-pucks.txt)
#if ((NUM_ROB != NUM_RESP)); then
#	printf '%s\n' "Not enough robots are responding. STOP" >&2
#	exit 1
#fi

echo "+-----------------------------------------------------------+"
echo "Checking all robots..."
./check-all

fi
done


for opt in "$@"
do
if [[ $opt == "--reset" || $opt == "-r" ]]; then

	./scp-all globalconfig

	echo "+-----------------------------------------------------------+"
	echo "Resetting Geth..."
	./reset-geth
	wait

	echo "+-----------------------------------------------------------+"
	echo "Resetting the Genesis Block..."
	./reset-genesis
	wait

	echo "+-----------------------------------------------------------+"
	echo "Synchronizing clocks..."
	TIME=$(date +"%F %T")
	./ssh-all "sudo timedatectl set-time '$TIME'"
	
fi
done

for opt in "$@"
do
if [[ $opt == "--start" || $opt == "-s" ]]; then

	echo "+-----------------------------------------------------------+"
	echo "Starting Experiment"

	./tmux-all "geth + main"
	
fi
done

# read -p "Press Enter when experiment is concluded"

# for opt in "$@"
# do
# if [[ $opt == "--collect" || $opt == "-c" ]]; then

# 	echo "+-----------------------------------------------------------+"
# 	echo "Collecting Logs"

# 	./collect-logs $LOG_FOLDER
	
# fi
# done
