#!/bin/bash
# Short script to open TMUX console with a pane for each robot
# Assumptions:
# - tmux is installed 

source ../globalconfig

NUM_ROB=$(wc -l < "$IDS_FILE")

# Collect all robot IP addresses in a list
ALL_IPS=()
for ID in $(cat "$IDS_FILE"); do
	ALL_IPS+=($PREFIX$ID)
done


tmux_ALL() {
	# Create an sequence of split window action for each robot IP
	split_list=()
	for IP in "${ALL_IPS[@]:1}"; do
	    split_list+=( split-pane ssh "$IP" ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new-session ssh "${ALL_IPS[0]}" ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 	
}

if [[ $# -eq 0 ]]; then 
	tmux_ALL
	tmux send-keys "cd $MAIN_DIR_ROBOTS" Enter

elif [[ $# -eq 1 ]]; then 

	if [[ $1 == "geth" ]]; then 
		tmux_ALL
		# Rename to GETH and setup Geth
		tmux kill-session -t GETH >/dev/null 2>&1
		tmux rename-session GETH
		tmux send-keys -t GETH "cd $MAIN_DIR_ROBOTS" Enter "./setup-geth" Enter

	elif [[ $1 == "python" ]]; then 
		tmux_ALL
		# Rename to PYTHON and setup the console
		tmux kill-session -t PYTHON >/dev/null 2>&1
		tmux rename-session PYTHON
		tmux send-keys -t PYTHON "cd $MAIN_DIR_ROBOTS/robots/controllers" Enter "python3 -i console.py" Enter

	elif [[ $1 == "main" ]]; then 
		tmux_ALL
		# Rename to MAINLOOP and setup mainloop
		tmux kill-session -t MAINLOOP >/dev/null 2>&1
		tmux rename-session MAINLOOP
		tmux send-keys -t MAINLOOP:0.$PANE "cd $MAIN_DIR_ROBOTS/$EXPERIMENT_FOLDER/controllers" Enter "python3 -i mainloop.py"

	elif [[ $1 == "start" || $1 == "-s" ]]; then  

		./tmux-all geth
		
		tmux_ALL
		BYZ_COUNT=0
		# Rename to MAINLOOP and setup mainloop
		tmux kill-session -t MAINLOOP >/dev/null 2>&1
		tmux rename-session MAINLOOP

		tmux set-option -w -t MAINLOOP synchronize-panes off
		for PANE in $(shuf -i 0-$(($NUM_ROB-1))); do
		  if [ $BYZ_COUNT -lt $NUM_BYZ ]; then
       tmux send-keys -t MAINLOOP:0.$PANE "cd $MAIN_DIR_ROBOTS/$EXPERIMENT_FOLDER/controllers" Enter "python3 -i mainloop.py --byz"
       let BYZ_COUNT++
       else
         tmux send-keys -t MAINLOOP:0.$PANE "cd $MAIN_DIR_ROBOTS/$EXPERIMENT_FOLDER/controllers" Enter "python3 -i mainloop.py"
      fi
		done
    tmux set-option -w -t MAINLOOP synchronize-panes on

   elif [[ $1 == "sync-on" ]]; then  
		echo "Synchronize-panes turned on"
		tmux set-option synchronize-panes on

	 elif [[ $1 == "sync-off" ]]; then  
		echo "Synchronize-panes turned off"
		tmux set-option synchronize-panes off
		    

  else
		tmux_ALL
		tmux send-keys "cd $MAIN_DIR_ROBOTS" Enter
	fi
fi