#!/bin/bash
# Short script to open TMUX console with a pane for each robot
# Assumptions:
# - tmux is installed 
# - The Pi-puck IDs are listed in pi-pucks.txt
source ../globalconfig


NUM_ROB=$(wc -l < pi-pucks.txt)

# Collect all robot IP addresses in a list
ALL_IPS=()
for ID in $(cat "$IDS_FILE"); do
	ALL_IPS+=(${PREFIX}${ID})
done


tmux_ALL() {
	# Create an sequence of split window action for each robot IP
	split_list=()
	for IP in "${ALL_IPS[@]:1}"; do
	    split_list+=( split-pane ssh "$IP" ';' select-layout even-vertical ';' )
	done

	# Define the terminal geometry (larger if there are many robots)
	geom="default"
	if [ $NUM_ROB -gt 8 ]; then
		geomX=$(( $NUM_ROB*8 ))
		geomY=$(( $NUM_ROB*5 ))
		geom="${geomX}x${geomY}"
	fi

	# Open the terminal and configure it 
	gnome-terminal --geometry="$geom" -- tmux new-session ssh "${ALL_IPS[0]}" ';' \
	    "${split_list[@]}" \
	    set-option -w synchronize-panes ';' \
		select-layout tiled ';' 
}

if [[ $# -eq 0 ]]; then 
	tmux_ALL

elif [[ $# -eq 1 ]]; then 

	if [[ $1 == "geth" ]]; then 
		tmux_ALL
		# Rename to GETH and setup Geth
		tmux kill-session -t GETH >/dev/null 2>&1
		tmux rename-session GETH
		tmux send-keys -t GETH "cd $MAIN_DIR_ROBOTS" Enter "./setup-geth"

	elif [[ $1 == "mainloop" ]]; then 
		tmux_ALL
		# Rename to MAINLOOP and setup mainloop
		tmux kill-session -t MAINLOOP >/dev/null 2>&1
		tmux rename-session MAINLOOP
		tmux send-keys -t MAINLOOP:0.$PANE "cd $MAIN_DIR_ROBOTS/control/robots" Enter "python3 -i mainloop.py"

	else 
		tmux_ALL
		# Rename to GETH and setup Geth
		tmux kill-session -t GETH >/dev/null 2>&1
		tmux rename-session GETH
		tmux send-keys -t GETH "cd $MAIN_DIR_ROBOTS" Enter "./setup-geth"
		
		tmux_ALL
		# Rename to MAINLOOP and setup mainloop
		tmux kill-session -t MAINLOOP >/dev/null 2>&1
		tmux rename-session MAINLOOP
		tmux send-keys -t MAINLOOP:0.$PANE "cd $MAIN_DIR_ROBOTS/control/robots" Enter "python3 -i mainloop.py"
	fi
fi