#!/bin/bash

# [PATHS]
export BASE_FOLDER="geth-pi-pucks"
export ROBOTS_NAME="pi"
export MONITOR_NAME="eksander"

export MAIN_DIR="/home/$USER/$BASE_FOLDER"
export MAIN_DIR_ROBOTS="/home/$ROBOTS_NAME/$BASE_FOLDER"

# [FILES]
export IDS_FILE="pi-pucks.txt"
export GENESIS_FILE="$MAIN_DIR/genesis/pipucks.json" 
export CONTRACT_FILE="$MAIN_DIR/control/robots/scs/experiment_volker.sol"
export CONTRACT_ABI="$MAIN_DIR/control/robots/scs/build/Estimation.abi"
export CONTRACT_ADDRESS=`cat $MAIN_DIR/control/robots/scs/contractAddress.txt`

# [NETWORKS]
export SUBNET="172.27.1"
# export SUBNET="192.168.1"
export MONITOR_ID="100"
export PREFIX="${ROBOTS_NAME}@${SUBNET}."

# [SC Parameters]
export DIMS=3
export NUMPT=100
export MAXLIFE=5
export MINREP=15
export RADIUS=10000 # 0.1
export DECIMAL_FACTOR=100000 # 1e5
export MAXUNVCLUSTER=3
# shellcheck disable=SC2155
export MINBALANCE=$(echo "200000000000000000000/$MAXUNVCLUSTER" | bc)