#!/bin/bash  
# Short script to perform calibration of the ground sensors from all robots listed
# Assumptions:
# - The Pi-puck IDs are listed in pi-pucks.txt
# - The robots are randomely placed in an arena with binary floor data

source ../../globalconfig

../tmux-all
tmux kill-session -t CALIBRATE >/dev/null 2>&1
tmux rename-session CALIBRATE
tmux send-keys -t CALIBRATE "cd $MAIN_DIR_ROBOTS/robots/calibration" Enter "python3 -i calibrate-cam.py"

read -p "Press Enter when robots finish collecting data"

# CAL_FILE="cam_bgr.csv"
# > $CAL_FILE
# for ID in $(cat "$IDS_FILE"); do
# 	ssh "${PREFIX}${ID}" "cat $MAIN_DIR_ROBOTS/robots/calibration/$ID.csv" >> $CAL_FILE 
# done

# sort -t  $'\t' -k 1 -o $CAL_FILE $CAL_FILE
# cat $CAL_FILE

# wait

# CAL_FILE="cam_hsv.csv"
# > $CAL_FILE
# for ID in $(cat "$IDS_FILE"); do
# 	ssh "${PREFIX}${ID}" "cat $MAIN_DIR_ROBOTS/robots/calibration/${ID}_hsv.csv" >> $CAL_FILE 
# done

# sort -t  $'\t' -k 1 -o $CAL_FILE $CAL_FILE
# cat $CAL_FILE

# wait