#!/bin/bash  
# Short script to perform calibration of the ground sensors from all robots listed
# Assumptions:
# - The Pi-puck IDs are listed in pi-pucks.txt
# - The robots are randomely placed in an arena with binary floor data

source ../../globalconfig


../tmux-all
tmux kill-session -t CALIBRATE >/dev/null 2>&1
tmux rename-session CALIBRATE
tmux send-keys -t CALIBRATE "cd $MAIN_DIR_ROBOTS/robots/calibration" Enter "python3 -i calibrate-cam.py"

read -p "Press Enter when robots finish collecting data"


for ID in $(cat "$IDS_FILE"); do
	scp -r pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/robots/calibration/${ID}_test_capture.jpg $MAIN_DIR/monitor/calibration &
	scp -r pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/robots/calibration/${ID}_one_time_test.jpg $MAIN_DIR/monitor/calibration &
	scp -r pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/robots/calibration/${ID}_raw_reading_test.jpg $MAIN_DIR/monitor/calibration &
	scp -r pi@172.27.1.$ID:$MAIN_DIR_ROBOTS/robots/calibration/${ID}_raw_reading_test_of.jpg $MAIN_DIR/monitor/calibration
done

wait
